package technical.test.product.service

import org.springframework.stereotype.Service

//https://www.rapidtables.com/web/color/RGB_Color.html
@Service
class RgbService {

    companion object {
        private val RGB_MAP = hashMapOf(
                "maroon" to "#800000",
                "dark red" to "#8B0000",
                "brown" to "#A52A2A",
                "firebrick" to "#B22222",
                "crimson" to "#DC143C",
                "red" to "#FF0000",
                "tomato" to "#FF6347",
                "coral" to "#FF7F50",
                "indian red" to "#CD5C5C",
                "light coral" to "#F08080",
                "dark salmon" to "#E9967A",
                "salmon" to "#FA8072",
                "light salmon" to "#FFA07A",
                "orange red" to "#FF4500",
                "dark orange" to "#FF8C00",
                "orange" to "#FFA500",
                "gold" to "#FFD700",
                "dark golden rod" to "#B8860B",
                "golden rod" to "#DAA520",
                "pale golden rod" to "#EEE8AA",
                "dark khaki" to "#BDB76B",
                "khaki" to "#F0E68C",
                "olive" to "#808000",
                "yellow" to "#FFFF00",
                "yellow green" to "#9ACD32",
                "dark olive green" to "#556B2F",
                "olive drab" to "#6B8E23",
                "lawn green" to "#7CFC00",
                "chart reuse" to "#7FFF00",
                "green yellow" to "#ADFF2F",
                "dark green" to "#006400",
                "green" to "#008000",
                "forest green" to "#228B22",
                "lime" to "#00FF00",
                "lime green" to "#32CD32",
                "light green" to "#90EE90",
                "pale green" to "#98FB98",
                "dark sea green" to "#8FBC8F",
                "medium spring green" to "#00FA9A",
                "spring green" to "#00FF7F",
                "sea green" to "#2E8B57",
                "medium aqua marine" to "#66CDAA",
                "medium sea green" to "#3CB371",
                "light sea green" to "#20B2AA",
                "dark slate gray" to "#2F4F4F",
                "teal" to "#008080",
                "dark cyan" to "#008B8B",
                "aqua" to "#00FFFF",
                "cyan" to "#00FFFF",
                "light cyan" to "#E0FFFF",
                "dark turquoise" to "#00CED1",
                "turquoise" to "#40E0D0",
                "medium turquoise" to "#48D1CC",
                "pale turquoise" to "#AFEEEE",
                "aqua marine" to "#7FFFD4",
                "powder blue" to "#B0E0E6",
                "cadet blue" to "#5F9EA0",
                "steel blue" to "#4682B4",
                "corn flower blue" to "#6495ED",
                "deep sky blue" to "#00BFFF",
                "dodger blue" to "#1E90FF",
                "light blue" to "#ADD8E6",
                "sky blue" to "#87CEEB",
                "light sky blue" to "#87CEFA",
                "midnight blue" to "#191970",
                "navy" to "#000080",
                "dark blue" to "#00008B",
                "medium blue" to "#0000CD",
                "blue" to "#0000FF",
                "royal blue" to "#4169E1",
                "blue violet" to "#8A2BE2",
                "indigo" to "#4B0082",
                "dark slate blue" to "#483D8B",
                "slate blue" to "#6A5ACD",
                "medium slate blue" to "#7B68EE",
                "medium purple" to "#9370DB",
                "dark magenta" to "#8B008B",
                "dark violet" to "#9400D3",
                "dark orchid" to "#9932CC",
                "medium orchid" to "#BA55D3",
                "purple" to "#800080",
                "thistle" to "#D8BFD8",
                "plum" to "#DDA0DD",
                "violet" to "#EE82EE",
                "fuchsia" to "#FF00FF",
                "magenta" to "#FF00FF",
                "orchid" to "#DA70D6",
                "medium violet red" to "#C71585",
                "pale violet red" to "#DB7093",
                "deep pink" to "#FF1493",
                "hot pink" to "#FF69B4",
                "light pink" to "#FFB6C1",
                "pink" to "#FFC0CB",
                "antique white" to "#FAEBD7",
                "beige" to "#F5F5DC",
                "bisque" to "#FFE4C4",
                "blanched almond" to "#FFEBCD",
                "wheat" to "#F5DEB3",
                "corn silk" to "#FFF8DC",
                "lemon chiffon" to "#FFFACD",
                "light golden rod yellow" to "#FAFAD2",
                "light yellow" to "#FFFFE0",
                "saddle brown" to "#8B4513",
                "sienna" to "#A0522D",
                "chocolate" to "#D2691E",
                "peru" to "#CD853F",
                "sandy brown" to "#F4A460",
                "burly wood" to "#DEB887",
                "tan" to "#D2B48C",
                "rosy brown" to "#BC8F8F",
                "moccasin" to "#FFE4B5",
                "navajo white" to "#FFDEAD",
                "peach puff" to "#FFDAB9",
                "misty rose" to "#FFE4E1",
                "lavender blush" to "#FFF0F5",
                "linen" to "#FAF0E6",
                "old lace" to "#FDF5E6",
                "papaya whip" to "#FFEFD5",
                "sea shell" to "#FFF5EE",
                "mint cream" to "#F5FFFA",
                "slate gray" to "#708090",
                "light slate gray" to "#778899",
                "light steel blue" to "#B0C4DE",
                "lavender" to "#E6E6FA",
                "floral white" to "#FFFAF0",
                "alice blue" to "#F0F8FF",
                "ghost white" to "#F8F8FF",
                "honeydew" to "#F0FFF0",
                "ivory" to "#FFFFF0",
                "azure" to "#F0FFFF",
                "snow" to "#FFFAFA",
                "black" to "#000000",
                "dim grey" to "#696969",
                "dim gray" to "#696969",
                "grey" to "#808080",
                "gray" to "#808080",
                "dark grey" to "#A9A9A9",
                "dark gray" to "#A9A9A9",
                "silver" to "#C0C0C0",
                "light grey" to "#D3D3D3",
                "light gray" to "#D3D3D3",
                "gainsboro" to "#DCDCDC",
                "white smoke" to "#F5F5F5",
                "white" to "#FFFFFF"
        )
    }

    fun lookupColor(basicColor : String) =
            RGB_MAP.getOrDefault(basicColor.toLowerCase(), "#FFFFFF")
}